// Code generated by counterfeiter. DO NOT EDIT.
package commandparserfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/stembuild/commandparser"
	"github.com/cloudfoundry-incubator/stembuild/construct/config"
)

type FakeVMPreparerFactory struct {
	VMPreparerStub        func(config.SourceConfig) commandparser.VmConstruct
	vMPreparerMutex       sync.RWMutex
	vMPreparerArgsForCall []struct {
		arg1 config.SourceConfig
	}
	vMPreparerReturns struct {
		result1 commandparser.VmConstruct
	}
	vMPreparerReturnsOnCall map[int]struct {
		result1 commandparser.VmConstruct
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVMPreparerFactory) VMPreparer(arg1 config.SourceConfig) commandparser.VmConstruct {
	fake.vMPreparerMutex.Lock()
	ret, specificReturn := fake.vMPreparerReturnsOnCall[len(fake.vMPreparerArgsForCall)]
	fake.vMPreparerArgsForCall = append(fake.vMPreparerArgsForCall, struct {
		arg1 config.SourceConfig
	}{arg1})
	fake.recordInvocation("VMPreparer", []interface{}{arg1})
	fake.vMPreparerMutex.Unlock()
	if fake.VMPreparerStub != nil {
		return fake.VMPreparerStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.vMPreparerReturns
	return fakeReturns.result1
}

func (fake *FakeVMPreparerFactory) VMPreparerCallCount() int {
	fake.vMPreparerMutex.RLock()
	defer fake.vMPreparerMutex.RUnlock()
	return len(fake.vMPreparerArgsForCall)
}

func (fake *FakeVMPreparerFactory) VMPreparerCalls(stub func(config.SourceConfig) commandparser.VmConstruct) {
	fake.vMPreparerMutex.Lock()
	defer fake.vMPreparerMutex.Unlock()
	fake.VMPreparerStub = stub
}

func (fake *FakeVMPreparerFactory) VMPreparerArgsForCall(i int) config.SourceConfig {
	fake.vMPreparerMutex.RLock()
	defer fake.vMPreparerMutex.RUnlock()
	argsForCall := fake.vMPreparerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVMPreparerFactory) VMPreparerReturns(result1 commandparser.VmConstruct) {
	fake.vMPreparerMutex.Lock()
	defer fake.vMPreparerMutex.Unlock()
	fake.VMPreparerStub = nil
	fake.vMPreparerReturns = struct {
		result1 commandparser.VmConstruct
	}{result1}
}

func (fake *FakeVMPreparerFactory) VMPreparerReturnsOnCall(i int, result1 commandparser.VmConstruct) {
	fake.vMPreparerMutex.Lock()
	defer fake.vMPreparerMutex.Unlock()
	fake.VMPreparerStub = nil
	if fake.vMPreparerReturnsOnCall == nil {
		fake.vMPreparerReturnsOnCall = make(map[int]struct {
			result1 commandparser.VmConstruct
		})
	}
	fake.vMPreparerReturnsOnCall[i] = struct {
		result1 commandparser.VmConstruct
	}{result1}
}

func (fake *FakeVMPreparerFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.vMPreparerMutex.RLock()
	defer fake.vMPreparerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVMPreparerFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commandparser.VMPreparerFactory = new(FakeVMPreparerFactory)
