// Code generated by counterfeiter. DO NOT EDIT.
package commandparserfakes

import (
	sync "sync"

	commandparser "github.com/cloudfoundry-incubator/stembuild/commandparser"
)

type FakeVmConstruct struct {
	CanConnectToVMStub        func() error
	canConnectToVMMutex       sync.RWMutex
	canConnectToVMArgsForCall []struct {
	}
	canConnectToVMReturns struct {
		result1 error
	}
	canConnectToVMReturnsOnCall map[int]struct {
		result1 error
	}
	PrepareVMStub        func() error
	prepareVMMutex       sync.RWMutex
	prepareVMArgsForCall []struct {
	}
	prepareVMReturns struct {
		result1 error
	}
	prepareVMReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVmConstruct) CanConnectToVM() error {
	fake.canConnectToVMMutex.Lock()
	ret, specificReturn := fake.canConnectToVMReturnsOnCall[len(fake.canConnectToVMArgsForCall)]
	fake.canConnectToVMArgsForCall = append(fake.canConnectToVMArgsForCall, struct {
	}{})
	fake.recordInvocation("CanConnectToVM", []interface{}{})
	fake.canConnectToVMMutex.Unlock()
	if fake.CanConnectToVMStub != nil {
		return fake.CanConnectToVMStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.canConnectToVMReturns
	return fakeReturns.result1
}

func (fake *FakeVmConstruct) CanConnectToVMCallCount() int {
	fake.canConnectToVMMutex.RLock()
	defer fake.canConnectToVMMutex.RUnlock()
	return len(fake.canConnectToVMArgsForCall)
}

func (fake *FakeVmConstruct) CanConnectToVMCalls(stub func() error) {
	fake.canConnectToVMMutex.Lock()
	defer fake.canConnectToVMMutex.Unlock()
	fake.CanConnectToVMStub = stub
}

func (fake *FakeVmConstruct) CanConnectToVMReturns(result1 error) {
	fake.canConnectToVMMutex.Lock()
	defer fake.canConnectToVMMutex.Unlock()
	fake.CanConnectToVMStub = nil
	fake.canConnectToVMReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVmConstruct) CanConnectToVMReturnsOnCall(i int, result1 error) {
	fake.canConnectToVMMutex.Lock()
	defer fake.canConnectToVMMutex.Unlock()
	fake.CanConnectToVMStub = nil
	if fake.canConnectToVMReturnsOnCall == nil {
		fake.canConnectToVMReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.canConnectToVMReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVmConstruct) PrepareVM() error {
	fake.prepareVMMutex.Lock()
	ret, specificReturn := fake.prepareVMReturnsOnCall[len(fake.prepareVMArgsForCall)]
	fake.prepareVMArgsForCall = append(fake.prepareVMArgsForCall, struct {
	}{})
	fake.recordInvocation("PrepareVM", []interface{}{})
	fake.prepareVMMutex.Unlock()
	if fake.PrepareVMStub != nil {
		return fake.PrepareVMStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.prepareVMReturns
	return fakeReturns.result1
}

func (fake *FakeVmConstruct) PrepareVMCallCount() int {
	fake.prepareVMMutex.RLock()
	defer fake.prepareVMMutex.RUnlock()
	return len(fake.prepareVMArgsForCall)
}

func (fake *FakeVmConstruct) PrepareVMCalls(stub func() error) {
	fake.prepareVMMutex.Lock()
	defer fake.prepareVMMutex.Unlock()
	fake.PrepareVMStub = stub
}

func (fake *FakeVmConstruct) PrepareVMReturns(result1 error) {
	fake.prepareVMMutex.Lock()
	defer fake.prepareVMMutex.Unlock()
	fake.PrepareVMStub = nil
	fake.prepareVMReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVmConstruct) PrepareVMReturnsOnCall(i int, result1 error) {
	fake.prepareVMMutex.Lock()
	defer fake.prepareVMMutex.Unlock()
	fake.PrepareVMStub = nil
	if fake.prepareVMReturnsOnCall == nil {
		fake.prepareVMReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.prepareVMReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVmConstruct) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.canConnectToVMMutex.RLock()
	defer fake.canConnectToVMMutex.RUnlock()
	fake.prepareVMMutex.RLock()
	defer fake.prepareVMMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVmConstruct) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commandparser.VmConstruct = new(FakeVmConstruct)
