// Code generated by counterfeiter. DO NOT EDIT.
package commandparserfakes

import (
	"sync"

	"github.com/cloudfoundry/stembuild/commandparser"
	"github.com/cloudfoundry/stembuild/construct/config"
)

type FakeVMPreparerFactory struct {
	VMPreparerStub        func(config.SourceConfig, commandparser.VCenterManager) (commandparser.VmConstruct, error)
	vMPreparerMutex       sync.RWMutex
	vMPreparerArgsForCall []struct {
		arg1 config.SourceConfig
		arg2 commandparser.VCenterManager
	}
	vMPreparerReturns struct {
		result1 commandparser.VmConstruct
		result2 error
	}
	vMPreparerReturnsOnCall map[int]struct {
		result1 commandparser.VmConstruct
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVMPreparerFactory) VMPreparer(arg1 config.SourceConfig, arg2 commandparser.VCenterManager) (commandparser.VmConstruct, error) {
	fake.vMPreparerMutex.Lock()
	ret, specificReturn := fake.vMPreparerReturnsOnCall[len(fake.vMPreparerArgsForCall)]
	fake.vMPreparerArgsForCall = append(fake.vMPreparerArgsForCall, struct {
		arg1 config.SourceConfig
		arg2 commandparser.VCenterManager
	}{arg1, arg2})
	fake.recordInvocation("VMPreparer", []interface{}{arg1, arg2})
	fake.vMPreparerMutex.Unlock()
	if fake.VMPreparerStub != nil {
		return fake.VMPreparerStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.vMPreparerReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVMPreparerFactory) VMPreparerCallCount() int {
	fake.vMPreparerMutex.RLock()
	defer fake.vMPreparerMutex.RUnlock()
	return len(fake.vMPreparerArgsForCall)
}

func (fake *FakeVMPreparerFactory) VMPreparerCalls(stub func(config.SourceConfig, commandparser.VCenterManager) (commandparser.VmConstruct, error)) {
	fake.vMPreparerMutex.Lock()
	defer fake.vMPreparerMutex.Unlock()
	fake.VMPreparerStub = stub
}

func (fake *FakeVMPreparerFactory) VMPreparerArgsForCall(i int) (config.SourceConfig, commandparser.VCenterManager) {
	fake.vMPreparerMutex.RLock()
	defer fake.vMPreparerMutex.RUnlock()
	argsForCall := fake.vMPreparerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVMPreparerFactory) VMPreparerReturns(result1 commandparser.VmConstruct, result2 error) {
	fake.vMPreparerMutex.Lock()
	defer fake.vMPreparerMutex.Unlock()
	fake.VMPreparerStub = nil
	fake.vMPreparerReturns = struct {
		result1 commandparser.VmConstruct
		result2 error
	}{result1, result2}
}

func (fake *FakeVMPreparerFactory) VMPreparerReturnsOnCall(i int, result1 commandparser.VmConstruct, result2 error) {
	fake.vMPreparerMutex.Lock()
	defer fake.vMPreparerMutex.Unlock()
	fake.VMPreparerStub = nil
	if fake.vMPreparerReturnsOnCall == nil {
		fake.vMPreparerReturnsOnCall = make(map[int]struct {
			result1 commandparser.VmConstruct
			result2 error
		})
	}
	fake.vMPreparerReturnsOnCall[i] = struct {
		result1 commandparser.VmConstruct
		result2 error
	}{result1, result2}
}

func (fake *FakeVMPreparerFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.vMPreparerMutex.RLock()
	defer fake.vMPreparerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVMPreparerFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commandparser.VMPreparerFactory = new(FakeVMPreparerFactory)
