# This is only here as an example and has not been tested!
#
# The build files must have already been generated by cmake.

LIBRSYNC_DIR=""
LIBRSYNC_BUILD_DIR=""

if [[ ! -d "$LIBRSYNC_DIR" ]]; then
	echo "Invalid LIBRSYNC_DIR: $LIBRSYNC_DIR"
fi

if [[ ! -d "$LIBRSYNC_BUILD_DIR" ]]; then
	echo "Invalid LIBRSYNC_BUILD_DIR: $LIBRSYNC_BUILD_DIR"
fi

rm -vf *.[ch]

cp $LIBRSYNC_BUILD_DIR/src/*.[ch]
cp $LIBRSYNC_DIR/src/*.[ch]
rm -v rdiff.c
