name: go
on:
  push:
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: stembuild/go.mod
    - name: Provide `StemcellAutomation.zip` for `go:embed` consumption in `assets` package
      run: |
        make generate-fake-stemcell-automation
      working-directory: stembuild
    - uses: golangci/golangci-lint-action@v8
      with:
        working-directory: stembuild
  test:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: stembuild/go.mod
    - name: Provide `StemcellAutomation.zip` for `go:embed` consumption in `assets` package
      run: |
        make generate-fake-stemcell-automation
      working-directory: stembuild
    # skip specs for "packager", "ovftool" because "ovftool" be installed
    - run: |
        go run github.com/onsi/ginkgo/v2/ginkgo run -r --keep-going --randomize-all --randomize-suites --skip-package integration,iaas_cli,ovftool,packager
      working-directory: stembuild
